spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456

graphql:
  servlet:
    mapping: /api/graphql
    enabled: true
    tools:
      schemaLocationPattern: "**/*.graphqls"

graphiql:
  enabled: true
  mapping: api/graphiql
  endpoint:
    graphql: /api/graphql
  cdn:
    enabled: true
    version: 0.12.0
